### ISSUE TITLE
gtlike execution failed with N10optimizers11OutOfBoundsE

### ISSUE THREAD

**Issue by Anuvab759** [fermi-lat/Likelihood#109]
I have been attempting to produce the data products using FERMI unibinned and binned analysis procedure, but in case of most of the time bins the gtlike step is failing with the following error: 

Computing TS values for each source (219 total)
.........................................Caught N10optimizers11OutOfBoundsE at the top level: Attempt to set the value outside of existing bounds.Computing TS values for each source 

I have checked the inputs again and again and the issue still persists. Could someone suggest what could be the resolution of this error? Has it something to do with the inputs? Has it something to do with the fermitools version or something else?

**Comment by nmirabal** [comment]
This has been reported before
https://github.com/fermi-lat/Fermitools-conda/issues/98
