### ISSUE TITLE
While running gta.setup(), gtltcube is generating an error and crashing

### ISSUE THREAD

**Issue by Sushanth99** [fermi-lat/Likelihood#113]
fermitools version 2.2.0
fermitools-data version 0.18
fermipy version 1.1.6
OS version MacOS 12.5.1, Darwin Kernel Version 21.6.0: (Macbook Air intel)

After running `gta = GTAnalysis('config.yaml',logging={'verbosity' : 3})` and then `gta.setup()`, the code is crashing with the following error: `IndexError: list index out of range`. In the log the following error is shown while running gtltcube : `GTBinnedAnalysis.run_gtapp(): Caught N5hoops12ApeExceptionE at the top level: Cannot open parameter file for gtltcube; Ape exception code 19 (at /Users/runner/miniforge3/conda-bld/fermitools_1655479516925/work/src/hoops/src/hoops_ape.cxx: 435)`

I am not sure what the issue here is. I tried re-installing fermipy but no luck. I am thinking it is related to `gtltcube`.

**Comment by nmirabal** [comment]
Closing this issue as it has already been posted in fermipy issues
https://github.com/fermiPy/fermipy/issues/497
