### ISSUE TITLE
Error while running gtlike

### ISSUE THREAD

**Issue by Lancelot-Ac** [fermi-lat/Likelihood#40]
packages in environment at /8T/han/software/miniconda2/envs/fermi:

Name                    Version                   Build 
fermitools                1.0.1            py27h39e3cac_0    
fermitools-data           0.16                          0    

Linux ISM.localdomain 2.6.32-358.el6.x86_64 #1 SMP Tue Jan 29 11:47:41 EST 2013 x86_64 x86_64 x86_64 GNU/Linux

I have been trying to follow the steps in Binned Likelihood Tutorial (https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/binned_likelihood_tutorial.html).
An error was reported when I ran gtlike:

(fermi) [han@ISM data_g2p2]$ export USE_BL_EDISP=true
(fermi) [han@ISM data_g2p2]$ gtlike
Warning in <TUnixSystem::SetDisplay>: DISPLAY not set, setting it to 58.192.54.78:0.0

WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).

Statistic to use (BINNED|UNBINNED) [BINNED]
Counts map file[none] g2p2_binned_srcmaps_Erange10_300gev.fits
Binned exposure map[none] g2p2_binned_allsky_expcube_Erange10_300gev.fits
Exposure hypercube file[none] g2p2_binned_ltcube_Erange10_300gev.fits
Source model file[] g2p2_input_model_Erange10_300gev.xml
Response functions to use[CALDB]
Optimizer (DRMNFB|NEWMINUIT|MINUIT|DRMNGB|LBFGS) [MINUIT] NEWMINUIT
Caught N5hoops10HexceptionE at the top level: Parameter edisp not found in parameter group gtlike (at /miniconda/conda-bld/fermitools_1551809382192/work/hoops/build/centos6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)

I have tried to remove gtlike.par in ~/pfiles/ but I got the same error. 
Besides, I am confused that the path " /miniconda/conda-bld/fermitools_1551809382192/work/hoops/build/centos6-x86_64-64bit-gcc48/src/hoops_group.cxx" seems to be not existent.

Thank you.

**Comment by jasercion** [comment]
Hi @Lancelot-Ac.  Please update to the latest version of the tools and let me know if the problem persists.  The parameter file that it is referencing should be updated in a more recent build  

`conda update -c conda-forge/label/cf201901 -c fermi fermitools-data`

**Comment by jasercion** [comment]
Since there has been no response I will assume this solved the issue.  @Lancelot-Ac please reopen if you find this is still a problem.
