### ISSUE TITLE
Occured Error by pylikelihood at v1.0.2.

### ISSUE THREAD

**Issue by FurutaT** [fermi-lat/Likelihood#41]
I had tried BinnedAnalysis of pyLikelihood by fermitools v1.0.2, but got following Errors.
When I running the same program by v1.0.1, I got good results.
Although I deleted .par file in ~/pfiles, Has not been resolved.

##############################################################
(fermi) [furuta@hozuki 2GeV-]$ conda list fermi
 packages in environment at /home/user/anaconda3/envs/fermi:

 Name                    Version                   Build  Channel
fermitools                1.0.2            py27h39e3cac_0    fermi
fermitools-data           0.17                          0    fermi

(fermi) [furuta@hozuki ]$ python
Python 2.7.14 | packaged by conda-forge | (default, Oct  5 2017, 14:19:56) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

>>> import pyLikelihood

WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).

>>> from BinnedAnalysis import *
>>> obs = BinnedObs(srcMaps=SRCM,expCube=LTCB,binnedExpMap=EXPM,irfs='P8R2_SOURCE_V6')
>>> 
>>> like1 = BinnedAnalysis(obs,XMLM,optimizer='DRMNGB')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/furuta/anaconda3/envs/fermi/lib/python2.7/site-packages/fermitools/BinnedAnalysis.py", line 169, in __init__
    delete_local_fixed=delete_local_fixed)
  File "/home/furuta/anaconda3/envs/fermi/lib/python2.7/site-packages/fermitools/BinnedAnalysis.py", line 43, in BinnedConfig
    kwargs.get('delete_local_fixed', False))
  File "/home/furuta/anaconda3/envs/fermi/lib/python2.7/site-packages/fermitools/pyLikelihood.py", line 5092, in __init__
    this = _pyLikelihood.new_BinnedLikeConfig(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_BinnedLikeConfig'.
  Possible C/C++ prototypes are:
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double,double,Likelihood::PsfIntegConfig::PSFIntegType,double,double,bool,int,bool,bool,bool,bool,bool)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double,double,Likelihood::PsfIntegConfig::PSFIntegType,double,double,bool,int,bool,bool,bool,bool)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double,double,Likelihood::PsfIntegConfig::PSFIntegType,double,double,bool,int,bool,bool,bool)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double,double,Likelihood::PsfIntegConfig::PSFIntegType,double,double,bool,int,bool,bool)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double,double,Likelihood::PsfIntegConfig::PSFIntegType,double,double,bool,int,bool)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double,double,Likelihood::PsfIntegConfig::PSFIntegType,double,double,bool,int)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double,double,Likelihood::PsfIntegConfig::PSFIntegType,double,double,bool)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double,double,Likelihood::PsfIntegConfig::PSFIntegType,double,double)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double,double,Likelihood::PsfIntegConfig::PSFIntegType,double)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double,double,Likelihood::PsfIntegConfig::PSFIntegType)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double,double)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig()
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(Likelihood::BinnedLikeConfig const &)

>>>

**Comment by nmirabal** [comment]
We are looking into this. Can you work with Fermitools v1.0.1 for now?.

**Comment by FurutaT** [comment]
I can work pylikelihood with v1.0.1 now.
But I do not work with changing to v1.0.2.

2019年5月1日(水) 2:24 nmirabal <notifications@github.com>:

**Comment by ichangzhi** [comment]
Same error on my macOS.

**Comment by dmalishev** [comment]
Same bug here. Trying to evercome it following the way it is done in analysis threads, i.e.:
import pyLikelihood
from BinnedAnalysis import *
obs =  BinnedObs(srcMaps='CenA_srcMaps.fits',expCube='CenA_ltcube.fits',binnedExpMap='CenA_BinnedExpMap.fits',irfs='CALDB')
like1 = BinnedAnalysis(obs,'CenA_model.xml',optimizer='MINUIT')

I've got another error

analysis = binnedAnalysis (obs, xml_model, optimizer='MINUIT')
  File "/home/tu/tu_tu/tu_pside01/FERMI/Soft/MiniConda3/envs/fermi/lib/python2.7/site-packages/fermitools/BinnedAnalysis.py", line 319, in binnedAnalysis
    irfs=irfs, phased_expmap=phased_expmap)
  File "/home/tu/tu_tu/tu_pside01/FERMI/Soft/MiniConda3/envs/fermi/lib/python2.7/site-packages/fermitools/BinnedAnalysis.py", line 51, in __init__
    expCube)
  File "/home/tu/tu_tu/tu_pside01/FERMI/Soft/MiniConda3/envs/fermi/lib/python2.7/site-packages/fermitools/BinnedAnalysis.py", line 114, in _obsDialog
    paramDict = MyOrderedDict()
NameError: global name 'MyOrderedDict' is not defined

**Comment by donhorner** [comment]
We have a beta release that should fix this issue.  It would be great if any of you could test it.  You can install the beta (we recommend creating a separate conda environment for testing) with the command:

conda create --name fermi_dev -c conda-forge/label/cf201901 -c fermi/label/beta -c fermi fermitools=1.0.5

Due to some metadata changes, it will probably also install fermitools-data and some other packages again. 

You can see full instructions on this page:
https://github.com/fermi-lat/Fermitools-conda/wiki/Testing-the-Fermitools

Let us know if it works.  Any feedback would be appreciated.

**Comment by FurutaT** [comment]
I tried pyLIkelihood after change Fermitools v1.0.5.
I didn't get any Error!!

2019年5月15日(水) 0:01 Don Horner <notifications@github.com>:

**Comment by donhorner** [comment]
@FurutaT Thanks for checking.  We'll probably officially release the new version early next week.

**Comment by jasercion** [comment]
A fix for this has been included in the latest release of the Fermitools (Fermitools=1.0.5).
