### ISSUE TITLE
gtlike

### ISSUE THREAD

**Issue by Sanjuphysics12** [fermi-lat/Likelihood#42]
I was doing unbinned likelihood analysis as described in the webpage "https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/likelihood_tutorial.html" taking the same data files provided in this page. I got an error at the end of 'gtlike' command i.e. " Floating point exception(core dumped). I cannot understand where the problem is and I have to resolve it.l

**Comment by nmirabal** [comment]
This seems to happen in certain operating systems. There is an alternative way to run the likelihood analysis within python that is more flexible. Please read the "Run the Likelihood Analysis" section in the following link
https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/python_tutorial.html
