### ISSUE TITLE
Occured Error by pylikelihood at v1.0.7.

### ISSUE THREAD

**Issue by FurutaT** [fermi-lat/Likelihood#43]
I updated Fermitools to v1.0.7, and tried pyLikelihood.
But, I got the same Error of v1.0.1...

(fermi) [furuta@hozuki first]$ conda list fermi
 packages in environment at /home/furuta/anaconda3/envs/fermi:

 Name                    Version                   Build  Channel
fermitools                1.0.7            py27h39e3cac_0    fermi
fermitools-data           0.17                          0    fermi

pyLikelihood
>>> import pyLikelihood
Warning in <TEnvRec::ChangeValue>: duplicate entry <Unix.*.Root.DynamicPath=.:$(MARSSYS)/lib> for level 1; ignored

WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).

>>> from BinnedAnalysis import *
>>> obs = BinnedObs(srcMaps=SRCM,expCube=LTCB,binnedExpMap=EXPM,irfs=IRFS)
>>> 
>>> like1 = BinnedAnalysis(obs,XMLM,optimizer='DRMNGB')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/furuta/anaconda3/envs/fermi/lib/python2.7/site-packages/fermitools/BinnedAnalysis.py", line 169, in __init__
    delete_local_fixed=delete_local_fixed)
  File "/home/furuta/anaconda3/envs/fermi/lib/python2.7/site-packages/fermitools/BinnedAnalysis.py", line 43, in BinnedConfig
    kwargs.get('delete_local_fixed', False))
  File "/home/furuta/anaconda3/envs/fermi/lib/python2.7/site-packages/fermitools/pyLikelihood.py", line 5092, in __init__
    this = _pyLikelihood.new_BinnedLikeConfig(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_BinnedLikeConfig'.
  Possible C/C++ prototypes are:
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double,double,Likelihood::PsfIntegConfig::PSFIntegType,double,double,bool,int,bool,bool,bool,bool,bool)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double,double,Likelihood::PsfIntegConfig::PSFIntegType,double,double,bool,int,bool,bool,bool,bool)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double,double,Likelihood::PsfIntegConfig::PSFIntegType,double,double,bool,int,bool,bool,bool)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double,double,Likelihood::PsfIntegConfig::PSFIntegType,double,double,bool,int,bool,bool)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double,double,Likelihood::PsfIntegConfig::PSFIntegType,double,double,bool,int,bool)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double,double,Likelihood::PsfIntegConfig::PSFIntegType,double,double,bool,int)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double,double,Likelihood::PsfIntegConfig::PSFIntegType,double,double,bool)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double,double,Likelihood::PsfIntegConfig::PSFIntegType,double,double)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double,double,Likelihood::PsfIntegConfig::PSFIntegType,double)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double,double,Likelihood::PsfIntegConfig::PSFIntegType)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double,double)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool,double)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool,bool)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool,bool)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool,bool)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(bool)
    Likelihood::BinnedLikeConfig::BinnedLikeConfig()
    Likelihood::BinnedLikeConfig::BinnedLikeConfig(Likelihood::BinnedLikeConfig const &)

**Comment by jasercion** [comment]
@FurutaT can you please update to Fermitools=1.2.23 and check to see if this issue still occurs?
