### ISSUE TITLE
RuntimeError: Covariance matrix size does not match the number of free parameters.

### ISSUE THREAD

**Issue by Sanjuphysics12** [fermi-lat/Likelihood#45]
I am getting this problem during likelihood analysis. How can  I fix this problem?

**Comment by Sanjuphysics12** [comment]
I am using the same XML file. Still, I am getting the mismatch.

**Comment by nmirabal** [comment]
Can you run the following analysis thread on your data?.
https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/python_tutorial.html

**Comment by Sanjuphysics12** [comment]
@nmirabal I am getting the same error when it's time to print 'fluxError'.

**Comment by nmirabal** [comment]
I haven't been able to reproduce this issue. Could you share the step by step commands and files?.

**Comment by Sanjuphysics12** [comment]
This problem is solved.
