### ISSUE TITLE
gtsrcmap: Problem on the creation of the source maps with the new spectral functions in the 4FGL

### ISSUE THREAD

**Issue by principe91** [fermi-lat/Likelihood#46]
The problem has been found in the creation of the source map by gtsrcmaps. It fail to extract the XML parameter (it says outside the specified bounds) for a source which has a PLSuperExpCutoff spectral function (a new spectral function first implemented in the 4FGL catalog: gll_psc_v19.fit). 

Reported problem:

2019-08-28 01:10:12 INFO    GTBinnedAnalysis.run_gtapp(): Creating source named 4FGL J1301.6+0834
2019-08-28 01:10:12 INFO    GTBinnedAnalysis.run_gtapp(): Parameter::extractDomData:
2019-08-28 01:10:12 INFO    GTBinnedAnalysis.run_gtapp(): In the XML description of parameter Cutoff, An attempt has been made to set the parameter value outside of the specified bounds.
2019-08-28 01:10:12 INFO    GTBinnedAnalysis.run_gtapp(): Caught St12out_of_range at the top level: Parameter::extractDomData:
2019-08-28 01:10:12 INFO    GTBinnedAnalysis.run_gtapp(): In the XML description of parameter Cutoff, An attempt has been made to set the parameter value outside of the specified bounds.

I'm using the Fermitools version 1.0.10
fermipy version 0.17.4
ScienceTools version ScienceTools-11-04-00

**Comment by nmirabal** [comment]
Can you download the latest version of make4FGL.py and repeat the whole analysis again?. Here is the link
https://fermi.gsfc.nasa.gov/ssc/data/analysis/user/make4FGLxml.py

**Comment by principe91** [comment]
> Can you download the latest version of make4FGL.py and repeat the whole analysis again?. Here is the link
> https://fermi.gsfc.nasa.gov/ssc/data/analysis/user/make4FGLxml.py

Hi Nestor, I did not get: where do I need to insert the script? Thanks

**Comment by nmirabal** [comment]
How do you generate the XML file required for gtsrcmaps?. Can you also please test  gtsrcmaps from the fermitools command line as explained in Section 8. Compute source map in the following link
https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/binned_likelihood_tutorial.html

**Comment by principe91** [comment]
I use the command gtsrcmaps. Also from command line I have the same problem. I have tried both to type the command In single line as well giving all the parameters from command line:

gtsrcmaps scfile=/nfs/farm/g/glast/g/diffuse/wavelets/data/catalogs/agn/m87/m87_marcello/data_11yr/ft2.fits sctable="SC_DATA" expcube=/nfs/farm/g/glast/g/diffuse/wavelets/data/catalogs/agn/m87/m87_marcello/an_11yr/ltcube_00.fits cmap=/nfs/farm/g/glast/g/diffuse/wavelets/data/catalogs/agn/m87/m87_marcello/an_11yr/ccube_00.fits srcmdl=/nfs/farm/g/glast/g/diffuse/wavelets/data/catalogs/agn/m87/m87_marcello/an_11yr/srcmdl_00.xml bexpmap=/nfs/farm/g/glast/g/diffuse/wavelets/data/catalogs/agn/m87/m87_marcello/an_11yr/bexpmap_00.fits wmap=none outfile=/nfs/farm/g/glast/g/diffuse/wavelets/data/catalogs/agn/m87/m87_marcello/an_11yr/srcmap_00.fits irfs="P8R3_SOURCE_V2" evtype=3 convol=yes resample=yes rfactor=2 minbinsz=0.05 ptsrc=yes psfcorr=yes emapbnds=no copyall=no chatter=3 clobber=yes debug=no gui=no mode="ql"

This is gtsrcmaps version HEAD
Using evtype=3 (i.e., FRONT/BACK irfs)
ResponseFunctions::load: IRF used: P8R3_SOURCE_V2
  event_types:  0  1
Creating source named m87
...
Creating source named 4FGL J1301.6+0834
Parameter::extractDomData:
In the XML description of parameter Cutoff, An attempt has been made to set the parameter value outside of the specified bounds.
Caught St12out_of_range at the top level: Parameter::extractDomData:
In the XML description of parameter Cutoff, An attempt has been made to set the parameter value outside of the specified bounds.

-------

gtsrcmaps

WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).

Exposure hypercube file[/nfs/farm/g/glast/g/diffuse/wavelets/data/catalogs/agn/m87/m87_marcello/an_11yr/ltcube_00.fits] 
Counts map file[/nfs/farm/g/glast/g/diffuse/wavelets/data/catalogs/agn/m87/m87_marcello/an_11yr/ccube_00.fits] 
Source model file[/nfs/farm/g/glast/g/diffuse/wavelets/data/catalogs/agn/m87/m87_marcello/an_11yr/srcmdl_00.xml] 
Binned exposure map[/nfs/farm/g/glast/g/diffuse/wavelets/data/catalogs/agn/m87/m87_marcello/an_11yr/bexpmap_00.fits] 
Source maps output file[/nfs/farm/g/glast/g/diffuse/wavelets/data/catalogs/agn/m87/m87_marcello/an_11yr/srcmap_00.fits] 
Response functions[P8R3_SOURCE_V2] 
Parameter::extractDomData:
In the XML description of parameter Cutoff, An attempt has been made to set the parameter value outside of the specified bounds.
Caught St12out_of_range at the top level: Parameter::extractDomData:
In the XML description of parameter Cutoff, An attempt has been made to set the parameter value outside of the specified bounds.

**Comment by nmirabal** [comment]
Could you follow this analysis thread for your source?
https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/binned_likelihood_tutorial.html

gtsrcmaps including source 4FGL J1301.6+0834 ran without any issues. It might be a problem with your XML file.

**Comment by jasercion** [comment]
Closing issue.
