### ISSUE TITLE
Update .par files to properly handled energy dispersion options.

### ISSUE THREAD

**Issue by eacharles** [fermi-lat/Likelihood#47]
We need to add some options to pfiles/gtdrm.par and we should change the help fields in a couple of other .par files to match.

**Comment by jasercion** [comment]
@eacharles were these all covered by this commit? https://github.com/fermi-lat/Likelihood/commit/ed3128746b964be3696e41fcee06f9e7be388924

**Comment by jasercion** [comment]
Closing issue.  Updates released in Fermitools-1.2.23.
