### ISSUE TITLE
gtlike 

### ISSUE THREAD

**Issue by jumplighter** [fermi-lat/Likelihood#49]
I try to run gtlike in linux and it succeed, but I can't see TS values of part of sources in the result.dat.
In the process,  it surely display THAT it had computed  the Ts value for each source. Can you give me some suggestions for me to see all the Ts values for each source?

**Comment by nmirabal** [comment]
TS values are recorded in results.dat  when parameters are set to free="1" in the xml file. In the results.dat file just do a search for TS value. Otherwise set parameters  free="1" for the source/sources you are interested in.

**Comment by jasercion** [comment]
Closing issue.
