### ISSUE TITLE
warning message when running gtlike

### ISSUE THREAD

**Issue by astropfk** [fermi-lat/Likelihood#50]
When I update the fermitools to the latest version 1.2.1, some errors occur in the step of gtlike. The other steps before gtlike work,  see text below. However, the gtike also can result in a right output. What's more, likelihood analysis with python works normally.

#######################################################################
(fermi) astropeng@astropeng-ThinkPad-T440p:~/test$ gtlike ftol=0.1 irfs=P8R3_SOURCE_V2 cmap=srcmaps.fits expcube=ltcube.fits srcmdl=model.xml statistic=binned optimizer=DRMNFB bexpmap=expmap.fits sfile=tmp.xml scfile=FT2.fits 

WARNING: version mismatch between CFITSIO header (v3.43) and linked library (v3.41).

Parameter ptsrc not found in parameter group gtlike (at /usr/share/miniconda/conda-bld/fermitools_1570220842412/work/hoops/build/debianstretch/sid-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 1 for parameter ptsrc
Parameter convol not found in parameter group gtlike (at /usr/share/miniconda/conda-bld/fermitools_1570220842412/work/hoops/build/debianstretch/sid-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 1 for parameter convol
Parameter resample not found in parameter group gtlike (at /usr/share/miniconda/conda-bld/fermitools_1570220842412/work/hoops/build/debianstretch/sid-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 1 for parameter resample
Parameter rfactor not found in parameter group gtlike (at /usr/share/miniconda/conda-bld/fermitools_1570220842412/work/hoops/build/debianstretch/sid-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 2 for parameter rfactor
Parameter minbinsz not found in parameter group gtlike (at /usr/share/miniconda/conda-bld/fermitools_1570220842412/work/hoops/build/debianstretch/sid-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 0.1 for parameter minbinsz

 NONDEFAULT VALUES....

 RFCTOL.... V(32) =   .3000000E-15

     I     INITIAL X(I)        D(I)

     1      .397307E+01      .100E+01
     2      .366691E+01      .100E+01
     3      .318346E+01      .100E+01
     4      .551277E+01      .100E+01
......

**Comment by jasercion** [comment]
This should be fixed in dev build 1.3.32.  @donhorner Can you please verify?

**Comment by jasercion** [comment]
@astropfk Can you please validate this fix as well?  It can be installed via the command

`conda install -c conda-forge/label/cf201901 -c fermi -c fermi/label/beta fermitools=1.2.32`

**Comment by jasercion** [comment]
Since there has been no response I will mark this issue closed.
