### ISSUE TITLE
Par files for gteffbkg, gttsmap, gttscube, gthealcube should include edisp_bins parameter.

### ISSUE THREAD

**Issue by eacharles** [fermi-lat/Likelihood#55]

**Comment by phbruel** [comment]
It doesn't seem that this issue has been fixed in Fermitools 1.3.4.

**Comment by Areustle** [comment]
I'm copying these lines

```
edisp,b,h,no,,,"Apply energy dispersion?"
edisp_bins,i,h,0,,,"Number of bins to consider energy dispersion for"
```

into the parfiles for each of {gteffbkg, gttsmap, gttscube, gthealcube}

**Comment by donhorner** [comment]
Closing the issue. The update par files were included in the latest release.
