### ISSUE TITLE
gtmodel ghost parameters

### ISSUE THREAD

**Issue by jballet** [fermi-lat/Likelihood#61]
When running gtmodel in fermitools 1.2.23), I guest the strange warnings
Parameter ptsrc not found in parameter group gtmodel (at /local/data/glitz1/gssctest/miniconda2/envs/build/conda-bld/fermitools_1580999712705/work/hoops/build/redhat6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 1 for parameter ptsrc
Parameter minbinsz not found in parameter group gtmodel (at /local/data/glitz1/gssctest/miniconda2/envs/build/conda-bld/fermitools_1580999712705/work/hoops/build/redhat6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 0.1 for parameter minbinsz
Parameter wmap not found in parameter group gtmodel (at /local/data/glitz1/gssctest/miniconda2/envs/build/conda-bld/fermitools_1580999712705/work/hoops/build/redhat6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Those parameters are not listed in the gtmodel.par file.
I have no idea what the /local/data/glitz1/gssctest directory is (it is not on our system).

**Comment by donhorner** [comment]
I think this the same problem as issue #50.  We have a beta that should get rid of the warnings.   It can be installed via the command

`conda install -c conda-forge/label/cf201901 -c fermi -c fermi/label/beta fermitools=1.2.32`

**Comment by jballet** [comment]
Absolutely. How could I find that? I tried looking for gtmodel in GitHub but found nothing.

**Comment by donhorner** [comment]
Did you mean to close this issue?  I wasn't sure what your last message meant.  You should be able to just run that conda command to update your fermitools environment to the beta version.

**Comment by jballet** [comment]
Yes, no need to keep duplicate issues.
