### ISSUE TITLE
gtmodel CMAP output has inconsistent header

### ISSUE THREAD

**Issue by jballet** [fermi-lat/Likelihood#62]
When launching gtmodel with the default CMAP mode, I get a 2D map all right, but the header is still that from a 3D map, inherited from the source maps input.
My header has NAXIS3=10, for example.

**Comment by jballet** [comment]
Actually I realize that the header has two series of NAXIS keywords. The first one is correct (with NAXIS=2) but the second one is inherited from the source maps and has NAXIS=3 and an NAXIS3 keyword. This foold ds9 into thinking that it is a 3D map.

**Comment by eacharles** [comment]
Fixed in branch Likelihood-62
