### ISSUE TITLE
gtexpmap failure

### ISSUE THREAD

**Issue by eacharles** [fermi-lat/Likelihood#70]
https://jira.slac.stanford.edu/projects/LK/issues/LK-133

**Comment by eacharles** [comment]
Ok.  This was due a numerical precision issue in defining the ranges of integration in computing the Psf integral.   The code tried to find upper and lower integration ranges by taking the cosine of the difference of two angles.   When that value was small, the numerical precision caused it to try to integrate from 1 to 1 and caused this error.
```

   double mup(std::cos(roi_radius + psi));
   double mum(std::cos(roi_radius - psi));
-   if (psi < roi_radius) {
+   if ( mum < 0.99 ) { 

      PsfIntegrand1 psfIntegrand1(sigma, gamma);
      firstIntegral = 
         st_facilities::GaussianQuadrature::dgaus8(psfIntegrand1, mum,
                                                   one, err, ierr);
   }

```

**Comment by donhorner** [comment]
Jean Ballet reports (using the Fermitools beta 1.3.0): "the gtexpmap call still fails with a very similar message 
Caught N13st_facilities18GaussianQuadrature15dgaus8ExceptionE at the top level: dgaus8 --- a and b are too nearly equal to allow normal integration. ans is set to 0 and ierr is set to -1."

**Comment by eacharles** [comment]
It is possible that there is still a case where this fails, but I fixed the previous failure.  
Can we make sure that the release include the code that fixes this.  (it is described in the GitHub issue).

-e

**Comment by jasercion** [comment]
I think I've identified the one remaining case where this would apply.  

`irfs/irfInterface/src/IPsf.cxx:181`

I'll make the update and incorporate it into the rebuilt beta

**Comment by eacharles** [comment]
Nice job.

-e

**Comment by jasercion** [comment]
This PR was also hanging.  It has now been merged.  https://github.com/fermi-lat/irfs/pull/11

**Comment by jballet** [comment]
I have tested FT 1.3.1 and it does not fail any more.
Of course this was a rare behavior so this single test cannot guarantee that gtexpmap does not fail in other rare cases.
But it definitely solves this particular failure.

**Comment by jasercion** [comment]
@jballet Great, I'm going to close this for now then.  If it happens again please reopen this issue.
