### ISSUE TITLE
gtsrcmaps/gtmodel does not understand projections properly

### ISSUE THREAD

**Issue by eacharles** [fermi-lat/Likelihood#71]
https://jira.slac.stanford.edu/projects/LK/issues/LK-105

**Comment by eacharles** [comment]
Ok, I think this was caused by the class astro/SkyProj not copying the crota keyword.  I'm put in a PR that I think fixes this.  The results fits files had the correct keywords set.   Still need to verify that the rotation are in fact correct.

**Comment by donhorner** [comment]
Jean Ballet reports (using the Fermitools beta 1.3.0): "looks good (I tested it on gtmodel, not gtsrcmaps, but I am pretty sure they go together). The model map is now correctly aligned with the counts map even when CROTA is not 0." 

Closing the issue.
