### ISSUE TITLE
EblAtten::PowerLaw

### ISSUE THREAD

**Issue by jballet** [fermi-lat/Likelihood#75]
It would be good if the EblAtten plug-in supported the PowerLaw model.
PowerLaw is the simplest of models and what is used for faint sources in the source catalog (easier to decorrelate Prefactor and Index by playing with Scale than in PowerLaw2).
Adding EBL attenuation requires at present converting the PowerLaw models either to LogParabola (with fixed beta=0) or to PowerLaw2.
It should be straightforward to create a EblAtten::PowerLaw model.

**Comment by eacharles** [comment]
Closing this as it is a duplicate
