### ISSUE TITLE
Parameter not found in group gtlike

### ISSUE THREAD

**Issue by omersajid9** [fermi-lat/Likelihood#86]
Hi,
I am trying to perform binned likelihood analysis on Crab Nebula's data using the gtlike command. But when I issue the command, I get the following error/warning at the beginning:

Parameter ptsrc not found in parameter group gtlike (at /local/data/glitz1/gssctest/miniconda2/envs/build/conda-bld/fermitools_1580999712705/work/hoops/build/redhat6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 1 for parameter ptsrc
Parameter convol not found in parameter group gtlike (at /local/data/glitz1/gssctest/miniconda2/envs/build/conda-bld/fermitools_1580999712705/work/hoops/build/redhat6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 1 for parameter convol
Parameter resample not found in parameter group gtlike (at /local/data/glitz1/gssctest/miniconda2/envs/build/conda-bld/fermitools_1580999712705/work/hoops/build/redhat6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 1 for parameter resample
Parameter rfactor not found in parameter group gtlike (at /local/data/glitz1/gssctest/miniconda2/envs/build/conda-bld/fermitools_1580999712705/work/hoops/build/redhat6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 2 for parameter rfactor
Parameter minbinsz not found in parameter group gtlike (at /local/data/glitz1/gssctest/miniconda2/envs/build/conda-bld/fermitools_1580999712705/work/hoops/build/redhat6-x86_64-64bit-gcc48/src/hoops_group.cxx: 67)
Using default value of 0.1 for parameter minbinsz

I have the latest fermitools version(1.2.23). I tried locating the directory but I dont have any /local/ directory.

**Comment by xiaoguoyaowan** [comment]
Hi, did you fix these errors? I have same problems on macOS 10.14.6 system.

**Comment by donhorner** [comment]
A new version of the Fermitools version 2.0.0 was released a few days ago that contains a fix for this issue.  Note that we recommend installing the 2.0 version into new environment rather than updating the existing one.  See the [release notes](https://github.com/fermi-lat/Fermitools-conda/wiki/Release-Notes) the [Install Instructions](https://github.com/fermi-lat/Fermitools-conda/wiki/Installation-Instructions#updating-existing-installation) for more.
