### ISSUE TITLE
ValueError: could not convert string to float - make4FGLxml.py

### ISSUE THREAD

**Issue by omersajid9** [fermi-lat/Likelihood#87]
Hi,
I am getting an error when I try to make source xml file of Crab data for likelihood analysis. The following is the error I get:

Traceback (most recent call last):
  File "make4FGLxml.py", line 825, in <module>
    if __name__=='__main__': cli()
  File "make4FGLxml.py", line 822, in cli
    sL.makeModel(args.galfile,args.galname,args.isofile,args.isoname,args.normsonly,args.extDir,args.radLim,args.maxRad,args.ExtraRad,args.sigFree,args.varFree,args.psForce,args.E2CAT,args.makeRegion,args.GIndexFree,args.writeDir,args.oldNames)
  File "make4FGLxml.py", line 69, in makeModel
    addSrcsXML(self,GDfile,GDname,ISOfile,ISOname,oldNames)
  File "make4FGLxml.py", line 156, in addSrcsXML
    elif float(src.getAttribute('TS_value'))>=sL.sig:
ValueError: could not convert string to float: 

I've also attached a screenshot:
![Screenshot from 2020-06-26 21-39-14](https://user-images.githubusercontent.com/67452047/85880579-ac12b880-b7f5-11ea-8aeb-9af8ae6f11de.png)

In order to find the problem, I edited the make4FGLxml.py file to print the TS values. I added print(src.getAttribute('TS_value')) to the code and found out that there is a non-float-string value. Please find attached the log file which shows the non-float-string value just before the error. I tried to perform the command with different data sets of Crab, but always get the same error.
[make4FGLxml_error.log](https://github.com/fermi-lat/Likelihood/files/4838188/make4FGLxml_error.log)

**Comment by joeastro** [comment]
Hello,

I tried to reproduce this issue, but was unsuccessful (i.e. it ran fine for me). Would it be possible to share your filtered events file, or list the inputs used to create it (source coordinates, time cuts, search radius, etc.)?

Thanks,
Joe Eggen

**Comment by joeastro** [comment]
Hello,

I was able to reproduce the error that you described, and am investigating the specific issue. In the meantime, I have a simple workaround that should get your project moving again. Simply use the following version of the catalog in your analysis:

https://fermi.gsfc.nasa.gov/ssc/data/access/lat/10yr_catalog/gll_psc_v23.fit

This is the latest version of the 4FGL catalog, made with 10 years of data. Note that it is the .fit version, whereas the one you were using was an .xml file.

I'll post a more detailed breakdown of the issue soon.

**Comment by omersajid9** [comment]
Hi, 

Thank you for your response. I am getting a similar error when I use the gll_psc_v23.fit file. 
![Screenshot from 2020-06-30 14-13-42](https://user-images.githubusercontent.com/67452047/86108190-4ca9f680-badc-11ea-9ae1-26e301f51f7e.png)
The query ID of the LAT data used here is L2006231434245FCA149A42. I couldn't attach the data files because of their size, but following are the .par files for the gtselect and gtmktime commands. 
[gtmktime.txt](https://github.com/fermi-lat/Likelihood/files/4850953/gtmktime.txt)
[gtselect.txt](https://github.com/fermi-lat/Likelihood/files/4850954/gtselect.txt)

I tried performing the command with a variety of data sets of Crab but got the same error each time.

**Comment by joeastro** [comment]
Hi,

It looks like you are using the extended photon files for your analysis - correct? I will download the same and repeat the analysis. For the record, using the normal (and much smaller) photon events files from the dataserver doesn't give me this issue, even when I use all the inputs that you supplied in your previous message.

~Joe

**Comment by joeastro** [comment]
Hi,

A couple of us at the FSSC have tried to reproduce your second error, but so far we have not been able to do so. As a sanity check, could you try downloading the catalog file gll_psc_23.fit and running the command again? Just checking to make sure the catalog file wasn't corrupted. The size of the file should be 5.2M after download.

For your convenience:
`wget https://fermi.gsfc.nasa.gov/ssc/data/access/lat/10yr_catalog/gll_psc_v23.fit`

**Comment by omersajid9** [comment]
Hi, 

I tried using simple Photons files and the link you provided, but am getting the same error, with both gll_psc_v23 and gll_psc_v21. 
![image](https://user-images.githubusercontent.com/67452047/86312710-be995180-bc3c-11ea-8598-6e8592ee8da9.png)
I have also attached onedrive link to the fits file used here:
https://1drv.ms/u/s!AsiKHKWHVppmkl4vHZswhtQrn4BY?e=8RCHcg

**Comment by joeastro** [comment]
Hi,

Unfortunately, we are still unable to reproduce the error you are getting, even when using the filtered events file that you provided. We are still trying to get to the bottom of this issue.

In the meantime, here is the the model file I was able to produce using the file that you provided in the preceding comment. Just change the .txt extension to .xml - GitHub doesn't support .xml attachments, apparently.
[crab_v23.txt](https://github.com/fermi-lat/Likelihood/files/4866536/crab_v23.txt)

Cheers,
Joe

**Comment by joeastro** [comment]
Hi,

We are still unable to reproduce the error you are seeing, but perhaps the following diagnostic test will help:

In the make4FGLxml.py script, find the the line that reads:
     if (dist<x and dist>=x-step) or (x==sL.roi[2]+10. and dist==x):

and insert the following line immediately after it:
          print(n)

This will print out the names of the sources in sequence as the script goes through them. Perhaps it will help us determine which source, if any, is causing the issue.

Cheers,
Joe

**Comment by omersajid9** [comment]
Hi,

Thank you for your reply. I get the following output when I edit the python script:
![Screenshot from 2020-07-07 22-36-14](https://user-images.githubusercontent.com/67452047/86820439-806bba00-c0a2-11ea-9f2d-6fd00eae4a89.png)

**Comment by omersajid9** [comment]
Hi,

I previously had installed Fermitools using miniconda, but now I reinstalled it using Anaconda and now the command runs fine using gll_psc_v23.fit file. I still have miniconda installed on my personal computer and the command doesn't work over there. So I believe the problem is somewhat related to miniconda.

Thank you for your help.

**Comment by donhorner** [comment]
FYI, Tyrel Johnson updated the make4FGLxml.py script so that using the XML version of the catalog will not result in the error originally reported.  We posted the update to [User Contributed Software](https://fermi.gsfc.nasa.gov/ssc/data/analysis/user/) page.
